refactor websocket to enable broadcast and add queue to tts
parmenashp/minecraft-narrator pull request #38
Opened 2024-01-18 09:28 UTC by daviirodrig

2024-01-18 22:49 UTC, alt-art requested changes

2024-01-18 22:49 UTC, alt-art commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
Colocar isso em uma função separada para que eu possa encaixar meu evento de configuração algo como:
```python
def handle_event(event: IncomingEvent, websocket: fastapi.WebSocket):
```

já aqui seria algo como:

```python
incoming_event = IncomingEvent(**json_data)
if incoming_event.event == Event.CONFIG:
    print(incoming_event.data)
    handle_config_event(json.loads(incoming_event.data, object_hook=lambda d: Config(**d)))
else:
    handle_event(incoming_event, ws)
```

2024-01-18 23:21 UTC, daviirodrig commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
não entendi a parte da função separada, da pra vc fazer como vc disse nesse segundo snippet e no else ali vc chama `event_handler.handle(incoming_event)` e dai segue o fluxo com o OutgoingAction?

```py
incoming_event = IncomingEvent(**json_data)
if incoming_event.event == Event.CONFIG:
    print(incoming_event.data)
    outgoing: OutgoingAction = handle_config_event(json.loads(incoming_event.data, object_hook=lambda d: Config(**d)))
else:
    outgoing: OutgoingAction = event_handler.handle(incoming_event)
```

2024-01-18 23:27 UTC, alt-art commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
No caso é para dar uma separada do resto do código, essa função separada que falei seria tudo que tem depois dessa linha `incoming_event = IncomingEvent(**json_data)`

2024-01-18 23:29 UTC, alt-art commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
Exemplo:

```python
def handle_event(event: IncomingEvent, websocket: fastapi.WebSocket):
    print("in:", event)
    outgoing = event_handler.handle(event=event)
    if outgoing.action == Action.IGNORE:
        return

    gpt_prompt = outgoing.data

    def background(event_loop):
        gpt_response_generator = chat.ask(gpt_prompt)
        full_response = tts.synthesize(gpt_response_generator)

        if full_response == "":
            response = OutgoingAction(
                action=Action.IGNORE,
                data="Erro ao gerar texto",
            )
        else:
            response = OutgoingAction(
                action=Action.SEND_CHAT,
                data=full_response,
            )

        asyncio.run_coroutine_threadsafe(websocket.send_json(response.model_dump()), event_loop)
        print("out:", response)

    loop = asyncio.get_event_loop()
    threading.Thread(target=background, kwargs={"event_loop": loop}).start()


def handle_config_event(data: Config):
    global_config.set_all(data)
    chat.set_config(global_config)
    tts.set_config(global_config)
    global_config.save()


@app.websocket("/ws")
async def websocket_endpoint(websocket: fastapi.WebSocket):
    await websocket.accept()
    async for json_data in websocket.iter_json():
        incoming_event = IncomingEvent(**json_data)
        if incoming_event.event == Event.CONFIG:
            print(incoming_event.data)
            handle_config_event(json.loads(incoming_event.data, object_hook=lambda d: Config(**d)))
        else:
            handle_event(incoming_event, websocket)
```

2024-01-18 23:31 UTC, alt-art commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
Esse código ai é oq eu tinha feito antes

2024-01-18 23:59 UTC, daviirodrig commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
hmm tendi, vou acabar colocando o evento de config aqui ja tbm então, ok?

2024-01-19 00:00 UTC, alt-art commented on backend/src/main.py
> +            incoming: IncomingEvent = IncomingEvent(**json_data)
boa

2024-01-19 01:49 UTC, alt-art approved these changes

2024-01-19 01:50 UTC, merged